GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmVyb25pY2EiLCJpYXQiOjE2MzA3NzY3NjN9.ISs7uD-1qDMzA3WxCO2_rUNXa7ol_z-an6X71sJ5Ti4

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmVyb25pY2EiLCJpYXQiOjE2MzA3Nzc2NzZ9.IjkZlsp1MVkU0UzLnJs8yHUl0l4AHAkRuXsquabaFRE"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Veronica"
}